[network]
n3h_persistence_path = "/tmp"
bootstrap_nodes = ["_BOOTSTRAP_"]

[[agents]]
id = "test_agent3"
name = "HoloTester3"
public_address = "HcSCIREnuI7mbpvmdi6Hd9hzJnPB39x7rb7B9rKQNc3q33n3D98IJciPiMj8jqr"
keystore_file = "conductor/holo_tester3.key"

[[dnas]]
id = "coolcats"
file = "dna-src/dist/dna-src.dna.json"

[[instances]]
id = "coolcats-instance3"
agent = "test_agent3"
dna = "coolcats"
[instances.storage]
type = "memory"

[[interfaces]]
id = "websocket-interface3"
[[interfaces.instances]]
id = "coolcats-instance3"
[interfaces.driver]
type = "websocket"
port = 8890

[logger]
type = "simple"
