[network]
n3h_persistence_path = "/tmp"
bootstrap_nodes = ["_BOOTSTRAP_"]

[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "HcSCICF4Hgx3K9frixvZexQde9Igv5uz83e5i9oQcYnRv8i8bPUQY4buSpndeka"
keystore_file = "conductor/holo_tester2.key"

[[dnas]]
id = "coolcats"
file = "dna-src/dist/dna-src.dna.json"

[[instances]]
id = "coolcats-instance2"
agent = "test_agent2"
dna = "coolcats"
[instances.storage]
type = "memory"

[[interfaces]]
id = "websocket-interface2"
[[interfaces.instances]]
id = "coolcats-instance2"
[interfaces.driver]
type = "websocket"
port = 8889

[logger]
type = "simple"
